### ISSUE TITLE
Update GitHub Changelog Generator to v0.0.10

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-io/spring-security-release-tools#26]
So that we can use the new feature for commercial releases https://github.com/spring-io/github-changelog-generator/issues/97

**Comment by sjohnr** [comment]
In the meantime, the following can be added to `build.gradle` to configure the update on a per-project basis:

```
dependencies {
	changelogGenerator 'spring-io:github-changelog-generator:0.0.10'
}
```

**Comment by sjohnr** [comment]
Note that version `0.0.10` requires a change to authentication. See spring-io/github-changelog-generator#104.
